force-app/main/default/objects/Aircraft__c/Aircraft__c.object-meta.xml
<CustomObject>
    <label>Aircraft</label>
    <nameField>
        <label>Aircraft Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aircraft__c/fields/IsAvailable__c.field-meta.xml
<CustomField>
    <fullName>IsAvailable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsAvailable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Aircraft__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Manufacturer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Airbus</fullName>
            </value>
            <value>
                <fullName>Boeing</fullName>
            </value>
            <value>
                <fullName>Cessna</fullName>
            </value>
            <value>
                <fullName>Gulfstream</fullName>
            </value>
            <value>
                <fullName>Bombardier</fullName>
            </value>
            <value>
                <fullName>Embraer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aircraft__c/fields/Model_Name__c.field-meta.xml
<CustomField>
    <fullName>Model_Name__c</fullName>
    <label>Model Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Manufacturer__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boeing 787</fullName>
            </value>
            <value>
                <fullName>Boeing 777</fullName>
            </value>
            <value>
                <fullName>Airbus A350</fullName>
            </value>
            <value>
                <fullName>Bombardier CRJ900</fullName>
            </value>
            <value>
                <fullName>Boeing 737</fullName>
            </value>
            <value>
                <fullName>Embraer E190</fullName>
            </value>
            <value>
                <fullName>Gulfstream G650</fullName>
            </value>
            <value>
                <fullName>Cessna Citation X</fullName>
            </value>
            <value>
                <fullName>Airbus A320</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aircraft__c/fields/Next_Scheduled_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Next_Scheduled_Maintenance__c</fullName>
    <label>Next Scheduled Maintenance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Aircraft__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Turboprop</fullName>
                <default>true</default>
                <label>Turboprop</label>
            </value>
            <value>
                <fullName>Turbojet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Aircraft__c.field-meta.xml
<CustomField>
    <fullName>Aircraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aircraft</label>
    <referenceTo>Aircraft__c</referenceTo>
    <relationshipLabel>Flight</relationshipLabel>
    <relationshipName>Flight</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Pre Flight</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Enroute</fullName>
            </value>
            <value>
                <fullName>Reached</fullName>
            </value>
            <value>
                <fullName>Deboarding</fullName>
            </value>
            <value>
                <fullName>Post Flight Check</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/Incident__c.object-meta.xml
<CustomObject>
    <label>Incident</label>
    <nameField>
        <displayFormat>IA-{000000}</displayFormat>
        <label>Incident Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incident__c/fields/Aircraft__c.field-meta.xml
<CustomField>
    <fullName>Aircraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aircraft</label>
    <referenceTo>Aircraft__c</referenceTo>
    <relationshipLabel>Incidents</relationshipLabel>
    <relationshipName>Incidents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Complete_By__c.field-meta.xml
<CustomField>
    <fullName>Complete_By__c</fullName>
    <label>Complete By</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Concerned_Issue__c.field-meta.xml
<CustomField>
    <fullName>Concerned_Issue__c</fullName>
    <label>Concerned Issue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fuel Check</fullName>
            </value>
            <value>
                <fullName>Oil level Check</fullName>
            </value>
            <value>
                <fullName>Tires and Brake</fullName>
            </value>
            <value>
                <fullName>Instruments Functional</fullName>
            </value>
            <value>
                <fullName>Emergency Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Describe_Incident__c.field-meta.xml
<CustomField>
    <fullName>Describe_Incident__c</fullName>
    <label>Describe Incident</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Incidents</relationshipLabel>
    <relationshipName>Incidents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Maintenance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Maintenance</label>
    <referenceTo>Maintenance__c</referenceTo>
    <relationshipLabel>Incidents</relationshipLabel>
    <relationshipName>Incidents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Pre_Flight_Task__c.field-meta.xml
<CustomField>
    <fullName>Pre_Flight_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pre Flight Task</label>
    <referenceTo>Pre_Flight_Task__c</referenceTo>
    <relationshipLabel>Incidents</relationshipLabel>
    <relationshipName>Incidents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Root_cause_analysis__c.field-meta.xml
<CustomField>
    <fullName>Root_cause_analysis__c</fullName>
    <label>Root cause analysis</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>M-{0000000000}</displayFormat>
        <label>Maintenance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Aircraft__c.field-meta.xml
<CustomField>
    <fullName>Aircraft__c</fullName>
    <label>Aircraft</label>
    <referenceTo>Aircraft__c</referenceTo>
    <relationshipLabel>Maintenances</relationshipLabel>
    <relationshipName>Maintenances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Objection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pre_Flight_Task__c/Pre_Flight_Task__c.object-meta.xml
<CustomObject>
    <label>Pre Flight Task</label>
    <nameField>
        <label>Pre Flight Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre Flight Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_Flight_Task__c/fields/Aircraft__c.field-meta.xml
<CustomField>
    <fullName>Aircraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aircraft</label>
    <referenceTo>Aircraft__c</referenceTo>
    <relationshipLabel>Pre Flight Tasks</relationshipLabel>
    <relationshipName>Pre_Flight_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pre_Flight_Task__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Pre Flight Tasks</relationshipLabel>
    <relationshipName>Pre_Flight_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/incidentController2.cls
public with sharing class incidentController2 {
   
@AuraEnabled(cacheable=true)
public static String getRecordTypeName(Id incidentId) {
    Incident__c incident = [
        SELECT RecordType.Name
        FROM Incident__c
        WHERE Id = :incidentId
        LIMIT 1
    ];
    return incident.RecordType.Name;

}
@AuraEnabled(cacheable=true)
public static Aircraft__c getAircraftDetails(Id incidentId) {
    Incident__c incident = [
        SELECT Aircraft__c
        FROM Incident__c
        WHERE Id = :incidentId
        LIMIT 1
    ];

    if (incident.Aircraft__c == null) {
        return null;
    }

    return [
        SELECT Id, Name, Model_Name__c, Manufacturer__c, Capacity__c, Type__c, IsAvailable__c, Next_Scheduled_Maintenance__c
        FROM Aircraft__c
        WHERE Id = :incident.Aircraft__c
    ];
}

    
    @AuraEnabled(cacheable=true)
    public static List<Incident__c> getIncidentsByAircraft(Id incidentId) {
        // Get the Aircraft__c from the given Incident__c record
        Incident__c incident = [
            SELECT Id, Aircraft__c , Complete_By__c FROM Incident__c WHERE Id = :incidentId LIMIT 1
        ];

        // Return all incidents related to that Aircraft
        return [
            SELECT Id, Name, Root_cause_analysis__c, Complete_By__c , Concerned_Issue__c, Status__c, Describe_Incident__c, RecordType.Name
            FROM Incident__c
            WHERE Aircraft__c = :incident.Aircraft__c
            AND Complete_By__c = :incident.Complete_By__c
            AND Id = :incident.Id
            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled
        public static void createIncident2(Id maintenanceId, String description, String issue) {
            
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Incident__c' AND Name = 'maintenance Incident' LIMIT 1];

        Incident__c newIncident = new Incident__c(
            Maintenance__c = maintenanceId,
            Describe_Incident__c = description,
            Concerned_Issue__c = issue,
            RecordTypeId = rt.Id
        );

            insert newIncident;
        }

        
        @AuraEnabled(cacheable=true)
        public static List<Incident__c> getIncidents() {
            return [SELECT Id, Aircraft__r.Name, Concerned_Issue__c, Status__c, Root_cause_analysis__c, Complete_By__c, Completed_Time__c, Describe_Incident__c FROM Incident__c];
        }

@AuraEnabled(cacheable=true)   
public static List<Incident__c> getDueOrOverdueIncidents() {
    return [
        SELECT Id, Aircraft__r.Name, Concerned_Issue__c, Status__c, Complete_By__c
        FROM Incident__c
        WHERE Complete_By__c <= :System.now()
        ORDER BY Complete_By__c ASC
    ];
}


@AuraEnabled(cacheable=true)
public static List<Pre_Flight_Task__c> getPendingPreFlightTasks() {
    return [
        SELECT Id, Name, Complete_By__c,Completed_On__c, Aircraft__r.Name, Flight__r.Name
        FROM Pre_Flight_Task__c
        WHERE Completed_On__c = NULL 
        AND Aircraft__r.Name != NULL 
        AND Flight__r.Name != NULL
        ORDER BY CreatedDate ASC
    ];
}


}